name: Build and deploy Node.js app to Azure Web App - mean-diss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install, build, and test frontend
      - name: Install, Build, and Test Frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          npm run test --if-present

      # Set up Node.js for backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install, build, and test backend
      - name: Install, Build, and Test Backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .  # Upload the whole directory or specify build directories

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E8D5F57906E441BCAE5BB65C2AD69F31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1653430A4454B1DA427258ABD894A9C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B693C2000FFA434A8BB8FE86387EEBC1 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mean-diss'  # Change to your Azure Web App name
          slot-name: 'Production'  # Change to a staging slot if needed
          package: .  # Path to the app's package (adjust if specific directories are needed)
